Wufoo project
Romanpr0g/LeverX_Tasks pull request #2
Opened 2024-01-11 14:02 UTC by Romanpr0g

Home page layout

2024-01-16 07:36 UTC, dzmitryFesik requested changes

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');
Please, download needed fonts and setup them locally

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +* {
Use normalize.css instead

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  /* color: #3a3a3a; */
Please review your changes before creating a PR

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +html {
Why html, but not body ?

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +.wrapper {
Too general class name
Please use more specific names

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  display:none;
It appears that you're not utilizing any formatters. Therefore, you have two options: either correct all places with incorrect formatting manually, or configure Prettier and apply it to all files in the project

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  font-size: 1.125rem;
Please keep consistency in your styles, e.g., by using either 'rem' or 'px' consistently across all instances

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  color: rgb(241, 68, 68);
Same as above

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  display: flex;
Please keep consistency in the order of style properties

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +.trusted-brands__wrapper:before {
Check usage of pseudo-elements

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  padding: 74.6px;
Please do not use fractional values, as this can lead to inconsistent rendering in different browsers

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  margin-right: auto;
Please, use the shorthand property if it's possible to
Check other places

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +.card--yellow * {
Please try not to use the wildcard selector

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  text-align: left;
`left` is the default value of the `text-align` property, or have I missed something?

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  margin-top: -0.5rem;
Can we avoid using negative margin here?

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +  left: -4%;
In positioning properties, try to avoid using percentages

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +}
What is it for?

2024-01-16 07:36 UTC, dzmitryFesik commented on css/style.css
> +label, a{ /*при наведении на стрелки или переключатели - курсор изменится*/
Avoid direct use of element selectors as recommended by BEM methodology
Please, check other places

2024-01-16 07:36 UTC, dzmitryFesik commented on index.html
> +      <div class="wrapper header__wrapper">
What is the purpose of the nested `div` in the `header` element?
As I can see, the nested `div` is redundant since it is the only child of the `header`

2024-01-16 07:36 UTC, dzmitryFesik commented on index.html
> +            ></iframe>
Self-closing tag

2024-01-22 09:04 UTC, Romanpr0g commented on css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');
fixed

2024-01-22 09:04 UTC, Romanpr0g commented on css/style.css
> +* {
fixed

2024-01-22 09:04 UTC, Romanpr0g commented on css/style.css
> +  /* color: #3a3a3a; */
fixed

2024-01-22 09:04 UTC, Romanpr0g commented on css/style.css
> +html {
fixed

2024-01-22 09:05 UTC, Romanpr0g commented on css/style.css
> +.wrapper {
fixed

2024-01-22 09:05 UTC, Romanpr0g commented on css/style.css
> +label, a{ /*при наведении на стрелки или переключатели - курсор изменится*/
fixed

2024-01-22 09:05 UTC, Romanpr0g commented on css/style.css
> +  display:none;
fixed

2024-01-22 09:05 UTC, Romanpr0g commented on css/style.css
> +  font-size: 1.125rem;
fixed

2024-01-22 09:05 UTC, Romanpr0g commented on css/style.css
> +  color: rgb(241, 68, 68);
fixed

2024-01-22 09:06 UTC, Romanpr0g commented on css/style.css
> +  display: flex;
fixed

2024-01-22 09:06 UTC, Romanpr0g commented on css/style.css
> +  padding: 74.6px;
fixed

2024-01-22 09:06 UTC, Romanpr0g commented on css/style.css
> +  margin-right: auto;
fixed

2024-01-22 09:06 UTC, Romanpr0g commented on css/style.css
> +.card--yellow * {
fixed

2024-01-22 09:06 UTC, Romanpr0g commented on css/style.css
> +  text-align: left;
fixed

2024-01-22 09:06 UTC, Romanpr0g commented on css/style.css
> +  margin-top: -0.5rem;
fixed

2024-01-22 09:07 UTC, Romanpr0g commented on css/style.css
> +  left: -4%;
fixed

2024-01-22 09:07 UTC, Romanpr0g commented on css/style.css
> +}
fixed

2024-01-22 09:07 UTC, Romanpr0g commented on index.html
> +      <div class="wrapper header__wrapper">
fixed

2024-01-24 09:08 UTC, dzmitryFesik requested changes

2024-01-24 09:08 UTC, dzmitryFesik commented on css/style.css
>  }
Please, remove fonts that are not used in the application from the `assets/fonts` folder

2024-01-24 09:08 UTC, dzmitryFesik commented on package.json
> +    "normalize.css": "^8.0.1"
If the project uses a local normalize.css file, I don't quite understand why a normalize.css dependency is needed

2024-02-02 13:55 UTC, dzmitryFesik approved these changes
Good job 👍

2024-02-19 12:34 UTC, merged